# Generated by Django 4.1.5 on 2023-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Cataegory/images/'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='MainCataegory/images/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(blank=True, upload_to='SubCataegory/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Products/images/'),
        ),
    ]
