# Generated by Django 4.1.5 on 2023-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_photo_alter_maincategory_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
