# Generated by Django 4.1.5 on 2023-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_category_description_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
